version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: campuscart_postgres
    restart: always
    environment:
      POSTGRES_USER: campuscart_user
      POSTGRES_PASSWORD: campuscart_password
      POSTGRES_DB: campuscart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
